### ISSUE TITLE
Form doesn't work at all: missing include {% include 'partials/form-messages.html.twig' %}?

### ISSUE THREAD

**Issue by kai47110815** [getgrav/grav-theme-agency#29]
Hello contact form doesn't work with GRAV 1.6x. I read the old issues, but nothing really works. While looking at \user\themes\agency\templates\modular\form.html.twig I noticed various includes on line 14, 48, 58, 64, etc. which aren't available at all (48, 58 are some variable generated ones).:

14 `{% include 'partials/form-messages.html.twig' %}`
48 ` {% include "forms/fields/#{field.type}/#{field.type}.html.twig" ignore missing %}`
58 `{% include "forms/fields/#{field.type}/#{field.type}.html.twig" ignore missing %}`
64 ` {% include "forms/fields/formname/formname.html.twig" %}`

**Comment by erdnuesse** [comment]
I recently fixed the form for me. 
As long as your email plugin is properly configured, this should work: 

```
title: contact
cache_enable: false
form:
    action: /home
    fields:
        name:
            label: Name
            classes: form-control
            placeholder: 'Enter your name'
            autofocus: 'off'
            autocomplete: 'on'
            type: text
            position: left
            validate:
                required: true
        email:
            label: Email
            classes: form-control
            position: left
            placeholder: 'Enter your email address'
            type: email
            validate:
                required: true
        message:
            label: Message
            classes: form-control
            position: right
            placeholder: 'Enter your message'
            type: textarea
            validate:
                required: true
    buttons:
        submit:
            type: submit
            value: Submit
        reset:
            type: reset
            value: Reset
    process:
        save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: '{% include ''forms/data.txt.twig'' %}'
            operation: create
        email:
            from: '{{ config.plugins.email.from }}'
            to: '{{ config.plugins.email.to }}'
            subject: '[Site Contact Form] {{ form.value.name|e }}'
            body: '{% include ''forms/data.html.twig'' %}'
        message: 'Thank you for getting in touch!'
        display: /home
        reset: true

```
